### ISSUE TITLE
nfc_gen_url output not  parsing

### ISSUE THREAD

**Issue by go4giraffe** [evilpete/flipper_toolbox#3]
file output by script isn't parsing with 0.69.2-1020-RM.
[RickRollFirmwareOriginal.nfc.txt](https://github.com/evilpete/flipper_toolbox/files/9844990/RickRollFirmwareOriginal.nfc.txt)
[rick_roll.nfc.txt](https://github.com/evilpete/flipper_toolbox/files/9844991/rick_roll.nfc.txt)

**Comment by evilpete** [comment]
thanks, will look into it...

**Comment by evilpete** [comment]
@go4giraffe   the rick_roll.nfc  file is in Unicode text, UTF-16  instead of utf-8/ascii

you can use the command [iconv](https://www.baeldung.com/linux/iconv-convert-from-utf-16le-to-utf-8) to character set conversion

`iconv  -f UTF-16 -t UTF-8  rick_roll.nfc  > rick_roll-fixed.nfc`

I'll see about adding code to the nfc_gen code to force ascii/utf-8
